### ISSUE TITLE
Exception when harvesting

### ISSUE THREAD

**Issue by Arsou33** [Arsou33/jarviews#28]
```
2022-11-22 02:57:57,059 INFO  [org.pee.jar.har.GavHarvester] (executor-thread-0) TOTAL : 626271 elements loaded
2022-11-22 02:57:57,074 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /admin/refresh failed, error id: 294d7b04-9970-4a7e-9857-d9d00c97eeba-1: java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "org.apache.maven.index.reader.Record.getLong(org.apache.maven.index.reader.Record$EntryKey)" is null
	at org.peekmoon.jarviews.harvester.GavHarvester.harvest(GavHarvester.java:71)
	at org.peekmoon.jarviews.harvester.GavHarvester_ClientProxy.harvest(Unknown Source)
	at org.peekmoon.jarviews.harvester.AdminController.refresh(AdminController.java:22)
	at org.peekmoon.jarviews.harvester.AdminController$quarkusrestinvoker$refresh_ef0a66babc5ddef7a31a12d860e33c5d9f7a27e0.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

2022-11-22 02:57:57,079 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-0) Request failed: java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "org.apache.maven.index.reader.Record.getLong(org.apache.maven.index.reader.Record$EntryKey)" is null
	at org.peekmoon.jarviews.harvester.GavHarvester.harvest(GavHarvester.java:71)
	at org.peekmoon.jarviews.harvester.GavHarvester_ClientProxy.harvest(Unknown Source)
	at org.peekmoon.jarviews.harvester.AdminController.refresh(AdminController.java:22)
	at org.peekmoon.jarviews.harvester.AdminController$quarkusrestinvoker$refresh_ef0a66babc5ddef7a31a12d860e33c5d9f7a27e0.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Arsou33** [comment]
Fix with #32
