### ISSUE TITLE
Remove duplication of avsc files

### ISSUE THREAD

**Issue by Arsou33** [Arsou33/jarviews#4]
Check if we have to remove apicurio dependency too

**Comment by Arsou33** [comment]
If we move gav.avsc in the src/main/avro of jarviews-commons, following exception is thrown when running project
`
2022-11-22 01:38:06,181 ERROR [io.sma.rea.mes.kafka] (smallrye-kafka-producer-thread-0) SRMSG18260: Unable to recover from the serialization failure (topic: gav), configure a SerializationFailureHandler to recover from errors.: java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Not an array: {"type":"record","name":"GavDetails","namespace":"org.peekmoon.jarviews","fields":[{"name":"groupId","type":{"type":"string","avro.java.string":"String"}},{"name":"artifactId","type":{"type":"string","avro.java.string":"String"}},{"name":"extension","type":{"type":"string","avro.java.string":"String"}},{"name":"classifier","type":["null",{"type":"string","avro.java.string":"String"}]},{"name":"version","type":{"type":"string","avro.java.string":"String"}}]} (through reference chain: org.peekmoon.jarviews.GavDetails["schema"]->org.apache.avro.Schema$RecordSchema["elementType"])
	at io.quarkus.kafka.client.serialization.ObjectMapperSerializer.serialize(ObjectMapperSerializer.java:47)
	at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:62)
	at io.smallrye.reactive.messaging.kafka.fault.SerializerWrapper.lambda$serialize$1(SerializerWrapper.java:56)
	at io.smallrye.reactive.messaging.kafka.fault.SerializerWrapper.wrapSerialize(SerializerWrapper.java:81)
	at io.smallrye.reactive.messaging.kafka.fault.SerializerWrapper.serialize(SerializerWrapper.java:56)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:1002)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:949)
	at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaProducer.lambda$send$5(ReactiveKafkaProducer.java:127)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateWithEmitter.subscribe(UniCreateWithEmitter.java:22)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Not an array: {"type":"record","name":"GavDetails","namespace":"org.peekmoon.jarviews","fields":[{"name":"groupId","type":{"type":"string","avro.java.string":"String"}},{"name":"artifactId","type":{"type":"string","avro.java.string":"String"}},{"name":"extension","type":{"type":"string","avro.java.string":"String"}},{"name":"classifier","type":["null",{"type":"string","avro.java.string":"String"}]},{"name":"version","type":{"type":"string","avro.java.string":"String"}}]} (through reference chain: org.peekmoon.jarviews.GavDetails["schema"]->org.apache.avro.Schema$RecordSchema["elementType"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:392)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:782)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4568)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3780)
	at io.quarkus.kafka.client.serialization.ObjectMapperSerializer.serialize(ObjectMapperSerializer.java:44)
	... 14 more
Caused by: org.apache.avro.AvroRuntimeException: Not an array: {"type":"record","name":"GavDetails","namespace":"org.peekmoon.jarviews","fields":[{"name":"groupId","type":{"type":"string","avro.java.string":"String"}},{"name":"artifactId","type":{"type":"string","avro.java.string":"String"}},{"name":"extension","type":{"type":"string","avro.java.string":"String"}},{"name":"classifier","type":["null",{"type":"string","avro.java.string":"String"}]},{"name":"version","type":{"type":"string","avro.java.string":"String"}}]}
	at org.apache.avro.Schema.getElementType(Schema.java:370)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:689)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	... 23 more
`
